curl -X GET http://localhost:4000/user \
-H "Content-Type: application/json" \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mjg2MzQwMTUsInVzZXJfaWQiOjJ9.DHUUuqeziSuTSY6Jq8jVFh9oFkkXd_c3BbjfNLpiC4g"

{
    "email":"test7@gmail.com",
    "password":"test"
}
